apps/backend/urls.py
from django.urls import path
from apps.backend.views import activate
from . import views

app_name = "backend"

urlpatterns = [
    path('', views.home.as_view(), name='home'),
    path('users/list', views.Users_List.as_view(), name='users_list'),
    path('users/create', views.Users_Create.as_view(), name='users_create'),
    path('users/update/<pk>', views.Users_Update.as_view(), name='users_update'),
    path('users/change-password', views.change_password, name='users_change_password'),
    path('users/delete/<pk>', views.Users_Delete.as_view(), name='users_delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from core.test import test
from apps.backend.views import register
from apps.frontend.sitemap import EventSitemap, PageSitemap, StaticViewSitemap

handler404 = 'apps.frontend.views.my_custom_page_not_found_view'
handler403 = 'apps.frontend.views.custom_permission_denied_view'
handler400 = 'apps.frontend.views.custom_bad_request_view'
handler500 = 'apps.frontend.views.custom_error_view'

sitemaps = {
    'events': EventSitemap,
    'pages': PageSitemap,
    'static': StaticViewSitemap
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),
    path('blog/', include('apps.blog.urls')),
    path('contact/', include('apps.contact.urls')),
    path('backend/', include('apps.backend.urls')),
    path('tests/', test, name='tests'),
    path('', include('apps.frontend.urls')),
    path("cookies/", include("apps.cookie_consent.urls")),
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [path('rosetta/', include('rosetta.urls'))]

if 'dynamic_preferences' in settings.INSTALLED_APPS:
    urlpatterns += [path('preferences/', include('dynamic_preferences.urls'))]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    

apps/backend/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField()

apps/backend/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def save(self, commit=True):
        user = super(RegisterUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.is_active = False
        if commit:
            user.save()
        return user

apps/backend/views.py
from django.shortcuts import render


from math import radians, cos, sin, asin, sqrt

def haversine(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points
    on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a))
    r = 6371 # Radius of earth in kilometers. Use 3956 for miles
    return c * r

center_point = [{'lat': -7.7940023, 'lng': 110.3656535}]
test_point = [{'lat': -7.79457, 'lng': 110.36563}]

lat1 = center_point[0]['lat']
lon1 = center_point[0]['lng']
lat2 = test_point[0]['lat']
lon2 = test_point[0]['lng']

radius = 1.00 # in kilometer

a = haversine(lon1, lat1, lon2, lat2)

print('Distance (km) : ', a)
if a <= radius:
    print('Inside the area')
else:
    print('Outside the area')

apps/backend/views/dashboard.py
from django.shortcuts import  render, redirect
from ..forms import RegisterUserForm
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth import get_user_model
from django.contrib import messages

from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_str
from core.email import UserRegisterEmail, VerificationEmail
from core.tokens import account_activation_token
from django.utils.translation import gettext as _
from dynamic_preferences.registries import global_preferences_registry
from core.decorators import check_recaptcha


User=get_user_model()

global_preferences = global_preferences_registry.manager()

class home(TemplateView):
    template_name = 'backend/index.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@check_recaptcha
def register(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid() and request.recaptcha_is_valid:
            user = form.save()
            context = {
                'request':request
            }
            if global_preferences['app__verification_email']:
                VerificationEmail(context, user).send()
                messages.success(request, _('verification email has been sent'))
            else:
                user.is_active = True
                user.save()
                UserRegisterEmail(context, user).send()
                login(request, user)
                messages.success(request, _('registration successful'))
            return redirect("frontend:home")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = RegisterUserForm()
    context = {
        "register_form":form,
        'site_key': settings.RECAPTCHA_PUBLIC_KEY if settings.RECAPTCHA_PUBLIC_KEY else None
    }
    return render (request, 'registration/registration_user.html', context)


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, _('Thank you for your email confirmation'))
        login(request, user)
        return redirect('frontend:home')
    else:
        messages.error(request, _('Activation link is invalid!'))
        return redirect('frontend:home')

apps/backend/views/users.py
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.utils.translation import gettext as _
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from dynamic_preferences.registries import global_preferences_registry

User=get_user_model()
global_preferences = global_preferences_registry.manager()


class Users_List(ListView):
    queryset = User.objects.filter(is_superuser=False)
    template_name = 'backend/users/list.html'
    context_object_name = 'users'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class Users_Create(CreateView):
    model = User
    template_name = 'backend/users/create.html'
    fields = [
        "username",
        "first_name",
        "last_name",
        "email",
        "password"
    ]

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse('backend:users_list')


class Users_Delete(DeleteView):
    model=User
    template_name='backend/users/delete.html'
    success_url=reverse_lazy("backend:users_list")

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

class Users_Update(UpdateView):
    model = User
    template_name = 'backend/users/update.html'
    fields = [
        "username",
        "first_name",
        "last_name",
        "email",
    ]

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse('backend:users_list')

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, _('Your password was successfully updated!'))
            return redirect('change_password')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'backend/users/change_password.html', {
        'form': form
    })

templates/backend/users/change_password.html
{% extends "backend/layout.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block navigator %}
    <li class="breadcrumb-item"><a href="{% url 'backend:home' %}">{% trans "home" %}</a></li>
    <li class="breadcrumb-item">{% trans "change password" %}</li>
{% endblock navigator %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="{% trans 'save' %}" class="btn btn-block btn-primary">
    </form>
{% endblock content %}

templates/backend/users/create.html
{% extends "backend/layout.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block navigator %}
    <li class="breadcrumb-item"><a href="{% url 'backend:home' %}">{% trans "home" %}</a></li>
    <li class="breadcrumb-item">{% trans "create user" %}</li>
{% endblock navigator %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="{% trans 'save' %}" class="btn btn-success">
        <a href="backend:users_list" class="btn btn-default">{% trans "see list" %}</a>
    </form>
{% endblock content %}

templates/backend/users/delete.html
{% extends "backend/layout.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block navigator %}
    <li class="breadcrumb-item"><a href="{% url 'backend:home' %}">{% trans "home" %}</a></li>
    <li class="breadcrumb-item">{% trans "delete user" %}</li>
{% endblock navigator %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>{% blocktrans with object=object %}Are you sure you want to delete "{{ object }}"?{% endblocktrans %}</p>
        <input type="submit" value="Confirm" class="btn btn-danger">
        <a href="{% url 'backend:users_list' %}" class="btn btn-default">{% trans "cancel"|title %}</a>
    </form>
{% endblock content %}

templates/backend/users/list.html
{% extends "backend/layout.html" %}

{% load i18n %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
{% endblock css %}

{% block navigator %}
    <li class="breadcrumb-item"><a href="{% url 'backend:home' %}">{% trans "home" %}</a></li>
    <li class="breadcrumb-item">{% trans "users list" %}</li>
{% endblock navigator %}

{% block content %}
    <table id="table_id" class="display">
        <thead>
            <tr>
                <th>{% trans "username"|capfirst %}</th>
                <th>{% trans "first name"|capfirst %}</th>
                <th>{% trans "last name"|capfirst %}</th>
                <th>{% trans "email"|capfirst %}</th>
                <th>{% trans "options"|capfirst %}</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.email }}</td>
                    <td>
                        <a href="{% url 'backend:users_update' user.pk %}" class="btn btn-primary" title="{% trans 'edit' %}"><i class="fas fa-edit"></i></a>
                        <a href="{% url 'backend:users_delete' user.pk %}" class="btn btn-danger" title="{% trans 'delete' %}"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

{% block js %}
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script>
        $(document).ready( function () {
            $('#table_id').DataTable({
                "language": {
                    "lengthMenu": "{% trans 'Display _MENU_ records per page' %}",
                    "zeroRecords": "{% trans 'Nothing found - sorry'|capfirst %}",
                    "info": "{% trans 'Showing page _PAGE_ of _PAGES_' %}",
                    "infoEmpty": "{% trans 'no records available'|capfirst %}",
                    "infoFiltered": "{% trans '(filtered from _MAX_ total records)'|capfirst %}",
                    "search": "{% trans 'search'|capfirst %}",
                }
            });
        } );
    </script>
{% endblock js %}

templates/backend/users/update.html
{% extends "backend/layout.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block navigator %}
    <li class="breadcrumb-item"><a href="{% url 'backend:home' %}">{% trans "home" %}</a></li>
    <li class="breadcrumb-item">{% trans "update user" %}</li>
{% endblock navigator %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="{% trans 'save' %}" class="btn btn-success">
        <a href="{% url 'backend:users_list' %}" class="btn btn-default">{% trans "back to the list" %}</a>
        <a href="{% url 'backend:users_delete' object.pk %}" class="btn btn-danger" style="float:right">{% trans "delete" %}</a>
    </form>
{% endblock content %}