apps/cookie_consent/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path
from django.views.decorators.csrf import csrf_exempt

from .views import CookieGroupAcceptView, CookieGroupDeclineView, CookieGroupListView

urlpatterns = [
    re_path(
        r"^accept/$",
        csrf_exempt(CookieGroupAcceptView.as_view()),
        name="cookie_consent_accept_all",
    ),
    re_path(
        r"^accept/(?P<varname>.*)/$",
        csrf_exempt(CookieGroupAcceptView.as_view()),
        name="cookie_consent_accept",
    ),
    re_path(
        r"^decline/(?P<varname>.*)/$",
        csrf_exempt(CookieGroupDeclineView.as_view()),
        name="cookie_consent_decline",
    ),
    re_path(
        r"^decline/$",
        csrf_exempt(CookieGroupDeclineView.as_view()),
        name="cookie_consent_decline_all",
    ),
    re_path(
        r"^$", CookieGroupListView.as_view(), name="cookie_consent_cookie_group_list"
    ),
]

apps/frontend/urls.py
from django.urls import path
from apps.backend.views import activate
from . import views

app_name = "frontend"

urlpatterns = [
    path('listado-de-eventos/', views.event_list, name='event_list'),
    path('<slug:slug>.html', views.PageDetailView.as_view(), name='page'),
    path('evento/<slug>.html', views.event_detail, name='event_detail'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('proyecto/igualarte-teatro-e-inclusion.html', views.project_igualarte_teatro, name='project_igualarte_teatro'),
    path('asociacion/latramoya.html', views.latramoya_view , name='latramoya_view'),
    path('quienes-somos/organigrama.html', views.organigramme_view, name='organigramme_view'),
    path('quienes-somos/equipo-profesional.html', views.team_professional_view, name='team_professional_view'),
    path('quienes-somos/colaboradores.html', views.team_volunteer_view, name='team_volunteer_view'),
    path('', views.home, name='home'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from core.test import test
from apps.backend.views import register
from apps.frontend.sitemap import EventSitemap, PageSitemap, StaticViewSitemap

handler404 = 'apps.frontend.views.my_custom_page_not_found_view'
handler403 = 'apps.frontend.views.custom_permission_denied_view'
handler400 = 'apps.frontend.views.custom_bad_request_view'
handler500 = 'apps.frontend.views.custom_error_view'

sitemaps = {
    'events': EventSitemap,
    'pages': PageSitemap,
    'static': StaticViewSitemap
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),
    path('blog/', include('apps.blog.urls')),
    path('contact/', include('apps.contact.urls')),
    path('backend/', include('apps.backend.urls')),
    path('tests/', test, name='tests'),
    path('', include('apps.frontend.urls')),
    path("cookies/", include("apps.cookie_consent.urls")),
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [path('rosetta/', include('rosetta.urls'))]

if 'dynamic_preferences' in settings.INSTALLED_APPS:
    urlpatterns += [path('preferences/', include('dynamic_preferences.urls'))]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    

apps/cookie_consent/models.py
# -*- coding: utf-8 -*-
import re

from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from .cache import delete_cache

COOKIE_NAME_RE = re.compile(r"^[-_a-zA-Z0-9]+$")
validate_cookie_name = RegexValidator(
    COOKIE_NAME_RE,
    _(
        "Enter a valid 'varname' consisting of letters, numbers"
        ", underscores or hyphens."
    ),
    "invalid",
)


class CookieGroup(models.Model):
    varname = models.CharField(
        _("Variable name"), max_length=32, validators=[validate_cookie_name]
    )
    name = models.CharField(_("Name"), max_length=100, blank=True)
    description = models.TextField(_("Description"), blank=True)
    is_required = models.BooleanField(
        _("Is required"),
        help_text=_("Are cookies in this group required."),
        default=False,
    )
    is_deletable = models.BooleanField(
        _("Is deletable?"),
        help_text=_("Can cookies in this group be deleted."),
        default=True,
    )
    ordering = models.IntegerField(_("Ordering"), default=0)
    created = models.DateTimeField(_("Created"), auto_now_add=True, blank=True)

    class Meta:
        verbose_name = _("Cookie Group")
        verbose_name_plural = _("Cookie Groups")
        ordering = ["ordering"]

    def __str__(self):
        return self.name

    def get_version(self):
        try:
            return str(self.cookie_set.all()[0].get_version())
        except IndexError:
            return ""

    def delete(self, *args, **kwargs):
        super(CookieGroup, self).delete(*args, **kwargs)
        delete_cache()

    def save(self, *args, **kwargs):
        super(CookieGroup, self).save(*args, **kwargs)
        delete_cache()


class Cookie(models.Model):
    cookiegroup = models.ForeignKey(
        CookieGroup,
        verbose_name=CookieGroup._meta.verbose_name,
        on_delete=models.CASCADE,
    )
    name = models.CharField(_("Name"), max_length=250)
    description = models.TextField(_("Description"), blank=True)
    path = models.TextField(_("Path"), blank=True, default="/")
    domain = models.CharField(_("Domain"), max_length=250, blank=True)
    created = models.DateTimeField(_("Created"), auto_now_add=True, blank=True)

    class Meta:
        verbose_name = _("Cookie")
        verbose_name_plural = _("Cookies")
        ordering = ["-created"]

    def __str__(self):
        return "%s %s%s" % (self.name, self.domain, self.path)

    @property
    def varname(self):
        return "%s=%s:%s" % (self.cookiegroup.varname, self.name, self.domain)

    def get_version(self):
        return self.created.isoformat()

    def delete(self, *args, **kwargs):
        super(Cookie, self).delete(*args, **kwargs)
        delete_cache()

    def save(self, *args, **kwargs):
        super(Cookie, self).save(*args, **kwargs)
        delete_cache()


ACTION_ACCEPTED = 1
ACTION_DECLINED = -1
ACTION_CHOICES = (
    (ACTION_DECLINED, _("Declined")),
    (ACTION_ACCEPTED, _("Accepted")),
)


class LogItem(models.Model):
    action = models.IntegerField(_("Action"), choices=ACTION_CHOICES)
    cookiegroup = models.ForeignKey(
        CookieGroup,
        verbose_name=CookieGroup._meta.verbose_name,
        on_delete=models.CASCADE,
    )
    version = models.CharField(_("Version"), max_length=32)
    created = models.DateTimeField(_("Created"), auto_now_add=True, blank=True)

    def __str__(self):
        return "%s %s" % (self.cookiegroup.name, self.version)

    class Meta:
        verbose_name = _("Log item")
        verbose_name_plural = _("Log items")
        ordering = ["-created"]

apps/cookie_consent/views.py
# -*- coding: utf-8 -*-
from django.core.exceptions import SuspiciousOperation
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView, View
from meta.views import Meta
from django.contrib.sites.shortcuts import get_current_site
from django.utils.translation import gettext as _

from .compat import RedirectURLMixin, url_has_allowed_host_and_scheme
from .models import CookieGroup
from .util import accept_cookies, decline_cookies


class CookieGroupListView(ListView):
    """
    Display all cookies.
    """

    model = CookieGroup

    def get_context_data(self, **kwargs):
        context = super(CookieGroupListView, self).get_context_data(**kwargs)
        current_site = get_current_site(self.request)
        meta = Meta(
            title = _('{} | Administrar preferencias de cookies '.format(current_site.name)),
            description = _(''),
            keywords='cookies',
            use_sites=True,
            image='frontend/images/logo.jpeg',
            extra_props={
                'designer': 'ecDesignStudio',
                'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
            },
            extra_custom_props=[
                ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
            ]
        )
        context['meta'] = meta
        return context


class CookieGroupBaseProcessView(RedirectURLMixin, View):
    def get_success_url(self):
        """
        If user adds a 'next' as URL parameter or hidden input,
        redirect to the value of 'next'. Otherwise, redirect to
        cookie consent group list
        """
        redirect_to = self.request.POST.get("next", self.request.GET.get("next"))
        if redirect_to and not url_has_allowed_host_and_scheme(
            url=redirect_to,
            allowed_hosts=self.get_success_url_allowed_hosts(),
            require_https=self.request.is_secure(),
        ):
            raise SuspiciousOperation("Unsafe open redirect suspected.")
        return redirect_to or reverse("cookie_consent_cookie_group_list")

    def process(self, request, response, varname):
        raise NotImplementedError()

    def post(self, request, *args, **kwargs):
        varname = kwargs.get("varname", None)
        if request.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest":
            response = HttpResponse()
        else:
            response = HttpResponseRedirect(self.get_success_url())
        self.process(request, response, varname)
        return response


class CookieGroupAcceptView(CookieGroupBaseProcessView):
    """
    View to accept CookieGroup.
    """

    def process(self, request, response, varname):
        accept_cookies(request, response, varname)


class CookieGroupDeclineView(CookieGroupBaseProcessView):
    """
    View to decline CookieGroup.
    """

    def process(self, request, response, varname):
        decline_cookies(request, response, varname)

    def delete(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

templates/cookie_consent/_cookie_group.html
{% load i18n %}
{% load cookie_consent_tags %}


<div class="cookie-group">
  <div class="cookie-group-title">
    <h3>{{ cookie_group.name }}</h3>

    {% if not cookie_group.is_required %}
      <div class="cookie-group-form">
       {% if request|cookie_group_accepted:cookie_group.varname %}
         <span class="cookie-consent-accepted">{% trans "Estado: Aceptado" %}</span>
       {% else %}
         <form class="cookie-consent-accept" action="{% url "cookie_consent_accept" cookie_group.varname %}" method="POST">
           {% csrf_token %}
           <input type="submit" value="{% trans "Aceptar" %}" class="btn btn-success">
         </form>
       {% endif %}

       {% if request|cookie_group_declined:cookie_group.varname %}
         <span class="cookie-consent-declined">{% trans "Estado: Rechazado" %}</span>
       {% else %}
         <form class="cookie-consent-decline" action="{% url "cookie_consent_decline" cookie_group.varname %}" method="POST">
           {% csrf_token %}
           <input type="submit" value="{% trans "Rechazar" %}" class="btn btn-danger">
         </form>
       {% endif %}
      </div>
    {% endif %}

  </div>

  <p>
    {{ cookie_group.description }}
  </p>


  <table>
  {% for cookie in cookie_group.cookie_set.all %}
   <tr>
     <th>
        {{ cookie.name }}
        {% if cookie.domain %}
          ({{ cookie.domain }})
        {% endif %}
     </th>
     <td>
       {% if cookie.description %}
        {{ cookie.description }}
       {% endif %}
     </td>
   </tr>
  {% endfor %}
  </table>

</div>

templates/cookie_consent/base.html
<html>
 <head></head>
 <body>
   {% block body %}
   {% endblock %}
 </body>
</html>

templates/cookie_consent/cookiegroup_list.html
{% extends "frontend/layout.html" %}

{% load i18n %}
{% load static %}

{% block css %}
    <style>
        .header {
            background-image:none;
            background-color: white;
            background-position: bottom center;
            background-repeat: no-repeat;
            background-size: cover;
            position: relative;
            padding: 120px 0 0px;
        }
        .section {
            padding-top: 20px;
            padding-bottom: 20px;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            margin-bottom: 1rem;
            background-color: transparent;
            color: #333;
        }
        thead th {
            text-align: left;
            background-color: #eee;
            border-bottom: 2px solid #ddd;
            padding: 0.5rem;
        }
        tbody td {
            border-bottom: 1px solid #ddd;
            padding: 0.5rem;
        }
        tbody tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        form.cookie-consent-decline, form.cookie-consent-accept {
            display: inline-block;
        }
    </style>
{% endblock css %}

{% block content %}
    <div class="header text-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 mx-auto">
                    <h1 class="mb-4">{% trans "Administrar preferencias de cookies" %}</h1>
                    <ul class="list-inline">
                        <li class="list-inline-item"><a class="text-default" href="{% url 'frontend:home' %}">{% trans "Inicio" %}
                        &nbsp; &nbsp; /</a></li>
                        <li class="list-inline-item text-primary">{% trans "Administrar preferencias de cookies" %}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <section class="section">
        <div class="container">
            <p>
                {% blocktrans %}
                    Utilizamos cookies para proporcionar y mantener nuestros servicios, hacer un seguimiento de las interrupciones y prevenir el spam, el fraude y los abusos, así como para medir la interacción de la audiencia y estadísticas de los sitios para entender cómo se utilizan nuestros servicios y mejorar su calidad.
                {% endblocktrans %}
            </p>
            {% for cookie_group in object_list  %}
                {% include "cookie_consent/_cookie_group.html" %}
            {% endfor %}
        </div>
    </section>
{% endblock %}