apps/blog/urls.py
from django.urls import path
from .views import PostDetail, PostList

app_name = 'blog'

urlpatterns = [
    path('tag/<slug:tag_slug>', PostList.as_view(), name='post_list_by_tag'),
    path('author/<slug:author_slug>', PostList.as_view(), name='post_list_by_author'),
    path('<slug:category_slug>/', PostList.as_view(), name='post_list_by_category'),
    path('<slug:slug>.html', PostDetail.as_view(), name='post_detail'),
    path('', PostList.as_view(), name='post_list'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from core.test import test
from apps.backend.views import register
from apps.frontend.sitemap import EventSitemap, PageSitemap, StaticViewSitemap

handler404 = 'apps.frontend.views.my_custom_page_not_found_view'
handler403 = 'apps.frontend.views.custom_permission_denied_view'
handler400 = 'apps.frontend.views.custom_bad_request_view'
handler500 = 'apps.frontend.views.custom_error_view'

sitemaps = {
    'events': EventSitemap,
    'pages': PageSitemap,
    'static': StaticViewSitemap
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),
    path('blog/', include('apps.blog.urls')),
    path('contact/', include('apps.contact.urls')),
    path('backend/', include('apps.backend.urls')),
    path('tests/', test, name='tests'),
    path('', include('apps.frontend.urls')),
    path("cookies/", include("apps.cookie_consent.urls")),
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [path('rosetta/', include('rosetta.urls'))]

if 'dynamic_preferences' in settings.INSTALLED_APPS:
    urlpatterns += [path('preferences/', include('dynamic_preferences.urls'))]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    

apps/blog/models.py
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

from tinymce.models import HTMLField as RichTextField
from sorl.thumbnail import ImageField
from meta.models import ModelMeta

from core.managers import InUseManager, IsApprovedManager
from core.abstract import SlugModel, PublishedModel, TimeStampedModel, ActiveModel

USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', User)

class Category(ActiveModel, SlugModel):
    name = models.CharField(_('name'), max_length=50, unique=True)

    objects = models.Manager()
    in_use = InUseManager()

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')


class Tag(ActiveModel, SlugModel):
    name = models.CharField(_('name'), max_length=50, unique=True)

    objects = models.Manager()
    in_use = InUseManager()

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')


class Author(ActiveModel, SlugModel):
    name = models.CharField(_('name'), max_length=255)

    objects = models.Manager()
    in_use = InUseManager()

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = _('author')
        verbose_name_plural = _('authors')


class Post(ActiveModel, SlugModel, PublishedModel, TimeStampedModel, ModelMeta):
    title = models.CharField(_('title'), max_length=255)
    subtitle = models.CharField(_('subtitle'), max_length=255, blank=True)

    excerpt = models.TextField(_('excerpt'),)
    text = RichTextField(_('text'),)

    featured = models.BooleanField(
        _('featured'),
        default=False,
        help_text=_('Display on the home page')
    )

    image = ImageField(
        _('imagen'),
        upload_to='blog_posts/',
        default='static/ecd_blog/images/default.png',
        blank=True
    )

    author = models.ForeignKey(
        Author,
        related_name='posts',
        verbose_name=_('autor'),
        on_delete=models.PROTECT
    )

    tags = models.ManyToManyField(
        Tag,
        related_name='posts',
        verbose_name=_('tags'),
        blank=True
    )

    category = models.ForeignKey(
        Category,
        related_name='posts',
        verbose_name=_('category'),
        on_delete=models.PROTECT,
        blank=True
    )

    meta_title = models.TextField(_('meta-title'), max_length=55, default='', help_text=_('with a maximum of 55 characters'))
    meta_description = models.TextField(_('meta-description'), max_length=140, default='', help_text=_('with a maximum of 140 characters'))
    _metadata = {
        'title': 'meta_title',
        'description': 'meta_description',
        'image': 'get_meta_image'
    }

    def get_meta_image(self):
        if self.image:
            return self.image.url

    def get_prev_post(self):
        return Post.published.filter(
            active=True,
            published_at__lt=self.published_at
        ).order_by(
            'published_at'
        ).last()

    def get_next_post(self):
        return Post.published.filter(
            active=True,
            published_at__gt=self.published_at
        ).order_by(
            'published_at'
        ).first()


    @property
    def list_of_approved_comments(self):
        objects = self.comments.all()
        objects = objects.filter(approved=True)
        return objects

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug':self.slug})

    class Meta:
        verbose_name = _('new')
        verbose_name_plural = _('news')
        ordering = ['published_at']


class Picture(models.Model):
    alt = models.CharField(_('alt'), max_length=255)
    image = ImageField(_('image'), upload_to='blog_galleries/')
    post = models.ForeignKey(
        Post,
        related_name='pictures',
        verbose_name=_('news'),
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )

    def __str__(self):
        return f'{self.alt}'

    class Meta:
        verbose_name = _('image')
        verbose_name_plural = _('images')

class Comment(ActiveModel, TimeStampedModel):
    #user = models.ForeignKey(
    #    USER_MODEL,
    #    related_name='comments',
    #    verbose_name=_('user'),
    #    blank=True,
    #    null=True,
    #    on_delete=models.PROTECT
    #)
    text = models.TextField(_('text'),)
    post = models.ForeignKey(
        Post,
        related_name='comments',
        verbose_name=_('news'),
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    approved = models.BooleanField(_('approved'), default=False)

    objects = models.Manager()
    is_approved = IsApprovedManager()
    # TODO eliminar approved y Is_aproved_manager para usar active que ya está

    # TODO que se muestre el contador en detalles y en los listados de solo los aprobados

    def __str__(self):
        return f'{self.text}'

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')
        ordering = ['approved', 'post', 'created_at']

apps/blog/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            "post",
            "text",
            #"user"
        )

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['text'].label = _("Escribe tu comentario")
        self.fields['post'].widget = forms.HiddenInput()
        #self.fields['user'].widget = forms.HiddenInput()

apps/blog/views.py
from django.shortcuts import redirect
from django.views import generic
from django.urls import reverse
from django.contrib import messages
from django.utils.translation import gettext as _

from meta.views import Meta
from .models import Post, Category, Tag, Author, Comment

from .forms import CommentForm


class PostList(generic.ListView):
    queryset = Post.published.order_by('-published_at')
    template_name = 'blog/post_list.html'
    meta = Meta(
        title = _('Blog de la Asociación APILAD'),
        description = 'La página de blog ofrece una amplia variedad de noticias sobre la asociación',
        keywords=['actividad', 'terapéutica', 'centro ocupacional', 'teatro'],
        use_sites=True,
        image='frontend/images/logo.jpeg',
        extra_props={
            'designer': 'ecDesignStudio',
            'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
        },
        extra_custom_props=[
            ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
        ]
    )

    def get(self, *args, **kwargs):
        queryset = Post.published.order_by('-published_at')
        if not queryset:
            return redirect('frontend:home')
        return super(PostList, self).get(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_slug = self.kwargs.get('category_slug', None)
        author_slug = self.kwargs.get('author_slug', None)
        tag_slug = self.kwargs.get('tag_slug', None)
        search = self.request.GET.get('search', None)

        if category_slug:
            category = Category.objects.get(slug=category_slug)
            context['filter_category'] = category
        if author_slug:
            author = Author.objects.get(slug=author_slug)
            context['filter_author'] = author
        if tag_slug:
            tag = Tag.objects.get(slug=tag_slug)
            context['filter_tag'] = tag
        if search:
            context['search'] = search
        context['categories'] = Category.in_use.all()[:4]
        context['meta'] = self.meta
        return context

    def get_queryset(self):
        category_slug = self.kwargs.get('category_slug', None)
        author_slug = self.kwargs.get('author_slug', None)
        tag_slug = self.kwargs.get('tag_slug', None)
        search = self.request.GET.get('search', None)

        objects = Post.published.all()
        if category_slug:
            objects = objects.filter(category__slug=category_slug)
        if author_slug:
            objects = objects.filter(author__slug=author_slug)
        if tag_slug:
            objects = objects.filter(tags__slug=tag_slug)
        if search:
            objects = objects.filter(title__icontains=search)

        return objects


class PostDetail(generic.edit.FormMixin, generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    form_class = CommentForm

    def get_initial(self):
        return {"post": self.get_object(), "user":self.request.user}

    def get_success_url(self):
        return reverse("blog:post_detail", kwargs={"slug": self.object.slug})

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        context['meta'] = self.get_object().as_meta(self.request)
        context['categories'] = Category.in_use.all()
        context['comments'] = Comment.is_approved.filter(post=self.object)

        try:
            next_post = self.object.get_next_post()
        except:
            next_post = None

        try:
            prev_post = self.object.get_prev_post()
        except:
            prev_post = None

        if prev_post:
            context['prev_post'] = prev_post

        if next_post:
            context['next_post'] = next_post

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, _('Tu comentario ha sido enviado'))
        form.save()
        return super().form_valid(form)

apps/blog/templates/blog/templatetags/blog_authors.html
{% load i18n %}

{% if authors %}
    <div class="box_detail booking">
        <div class="price">
            <h3 style="margin:0px">{% trans "autores"|capfirst %}</h3>
        </div>
        <ul class="cats">
            {% for author in authors %}
                <li><a href="{% url 'blog:post_list_by_author' author.slug %}">{{ author.name|capfirst }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

apps/blog/templates/blog/templatetags/blog_categories.html
{% load i18n %}

{% if categories %}
    <div class="box_detail booking bg_color_1">
        <div class="price">
            <h3 style="margin:0px">{% trans "categorías"|capfirst %}</h3>
        </div>
        <ul class="cats">
            {% for category in categories %}
                <li><a href="{% url 'blog:post_list_by_category' category.slug %}">{{ category.name|capfirst }}</a></li>
            {% endfor %}
            {% if categories.count > 4 %}
                <li><a href="{% url 'blog:post_list' %}">{% trans 'see all'|capfirst %}</a></li>
            {% endif %}
        </ul>
    </div>
{% endif %}

apps/blog/templates/blog/templatetags/blog_featured.html
{% load i18n %}
{% comment %}

    {% if show_title %}
    <div class="container">
      <div>
            <h2>
                {% if title %}
                    {{ title }}
                {% else %}
                    {% trans "Featured blog posts " %}
                {% endif %}
            </h2>
      </div>
    </div>
    {% endif %}

    {% for post in posts %}
        <article>
            <h2><a href="{% url 'blog:post_detail' post.slug %}">{{ post.title }}</a></h2>
            <div>
                <small>
                    <strong>{% trans "Author" %}:</strong>
                    <a href="{% url 'blog:post_list_by_author' post.author.slug %}">{{ post.author }}</a>
                    <strong>{% trans "Tags" %}:</strong>
                    {% for tag in post.tags.all %}
                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
                    {% empty %}
                        {% trans "No tags" %}
                    {% endfor %}
                </small>
            </div>
            <img src="{{ post.image.url }}" width="200">
            <p>{{ post.excerpt }}</p>
        </article>
        <hr>
    {% empty %}
        {% trans "No posts found" %}
    {% endfor %}
    {% if show_view_all %}
        <a href="{% url 'blog:post_list' %}">{% trans "Show all" %}</a>
    {% endif %}
{% endcomment %}

{% if posts %}

    <div class="bg_color_1">
        <div class="container margin_80_55">
            <div class="main_title_2">
                <span><em></em></span>
                <h3>{% trans "noticias y eventos"|capfirst %}</h3>
                <p>{% trans "Te lo contamos todo: eventos, noticias y toda la actualidad de Skeirrum"|capfirst %}</p>
            </div>
            <div class="row">
                {% for post in posts %}
                    <div class="col-lg-6">
                        <a class="box_news" href="{% url 'blog:post_detail' post.slug %}">
                            <figure><img src="{{ post.image.url }}" alt="{{ post.slug }}">
                                <figcaption><strong>{{ post.created_at|date:'d'}}</strong>{{ post.created_at|date:'M'}}</figcaption>
                            </figure>
                            <ul>
                                <li>{{ post.author }}</li>
                                <li>{{ post.created_at|date:'d.m.y'}}</li>
                            </ul>
                            <h4>{{ post.title|title }}</h4>
                            <p>{{ post.excerpt|truncatewords:20 }}</p>
                        </a>
                    </div>
                {% endfor %}
            </div>
            <!-- /row -->
            <p class="btn_home_align"><a href="{% url 'blog:post_list' %}" class="btn_1 rounded">{% trans "ver más noticias"|capfirst %}</a></p>
        </div>
        <!-- /container -->
    </div>

{% endif %}

apps/blog/templates/blog/templatetags/blog_menu.html
{% load i18n %}

{% if show %}
  <li>
    <span><a href="{% url 'blog:post_list' %}">{% trans "actualidad"|title %}</a></span>
  </li>
{% endif %}

apps/blog/templates/blog/templatetags/blog_search.html
{% load i18n %}

{% if show %}
    <div class="gtr-uniform">
        <form method="GET" id="search_form" accept-charset="utf-8" action="{% url 'blog:post_list' %}">
            <div class="form-group">
                <input name="search" id="search" type="text" placeholder="{% if search %}{{ search }}{%else%}{% trans 'terminos de búsqueda'|capfirst %}{% endif %}" />
            </div>
            <br>
            <button type="submit" class="button primary fit">{% trans 'buscar'|capfirst %}</button>
        </form>
    </div>
{% endif %}

apps/blog/templates/blog/templatetags/blog_sidebar.html
{% load blog_tags %}

{% blog_search search %}

{% if categories %}{% blog_categories %}{% endif %}
{% comment %}
    {% if authors %}{% blog_authors %}{% endif %}
{% endcomment %}
{% if tags %}{% blog_tags %}{% endif %}

apps/blog/templates/blog/templatetags/blog_tags.html
{% load i18n %}

{% if tags %}
    <div class="box_detail booking">
        <div class="price">
            <h3 style="margin:0px">{% trans "etiquetas"|capfirst %}</h3>
        </div>
        <div class="tags">
            {% for tag in tags %}
                {% widthratio tag.posts_count max_count 10 as size%}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}" style="font-size:calc(12px + {{ size }}px)">{{ tag.name|capfirst }} {{ tag.posts_count}}</a>
            {% endfor %}
            <a href="{% url 'blog:post_list' %}">{% trans 'todas'|title %}</a>
        </div>
    </div>
{% endif %}