apps/contact/urls.py
from django.urls import path
from .views import contact

app_name = 'contact'

urlpatterns = [
    path('', contact, name='home'),
]

apps/frontend/urls.py
from django.urls import path
from apps.backend.views import activate
from . import views

app_name = "frontend"

urlpatterns = [
    path('listado-de-eventos/', views.event_list, name='event_list'),
    path('<slug:slug>.html', views.PageDetailView.as_view(), name='page'),
    path('evento/<slug>.html', views.event_detail, name='event_detail'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('proyecto/igualarte-teatro-e-inclusion.html', views.project_igualarte_teatro, name='project_igualarte_teatro'),
    path('asociacion/latramoya.html', views.latramoya_view , name='latramoya_view'),
    path('quienes-somos/organigrama.html', views.organigramme_view, name='organigramme_view'),
    path('quienes-somos/equipo-profesional.html', views.team_professional_view, name='team_professional_view'),
    path('quienes-somos/colaboradores.html', views.team_volunteer_view, name='team_volunteer_view'),
    path('', views.home, name='home'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from core.test import test
from apps.backend.views import register
from apps.frontend.sitemap import EventSitemap, PageSitemap, StaticViewSitemap

handler404 = 'apps.frontend.views.my_custom_page_not_found_view'
handler403 = 'apps.frontend.views.custom_permission_denied_view'
handler400 = 'apps.frontend.views.custom_bad_request_view'
handler500 = 'apps.frontend.views.custom_error_view'

sitemaps = {
    'events': EventSitemap,
    'pages': PageSitemap,
    'static': StaticViewSitemap
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),
    path('blog/', include('apps.blog.urls')),
    path('contact/', include('apps.contact.urls')),
    path('backend/', include('apps.backend.urls')),
    path('tests/', test, name='tests'),
    path('', include('apps.frontend.urls')),
    path("cookies/", include("apps.cookie_consent.urls")),
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [path('rosetta/', include('rosetta.urls'))]

if 'dynamic_preferences' in settings.INSTALLED_APPS:
    urlpatterns += [path('preferences/', include('dynamic_preferences.urls'))]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    

apps/frontend/views.py
'''Views for the frontend app'''

from django.shortcuts import render, get_object_or_404
from django.conf import settings
from django.contrib import messages
from django.views.generic import DetailView
from django.contrib.sites.shortcuts import get_current_site
from django.utils.translation import gettext as _
from django.shortcuts import redirect

from meta.views import Meta

from apps.cookie_consent.util import get_cookie_value_from_request
from .models import Page, Event


def home(request):
    '''Home view for the frontend app'''
    def _should_set_cookie() -> bool:
        if "force" in request.GET:
            return True
        cookie_value = get_cookie_value_from_request(request, "optional")
        return cookie_value is True

    current_site = get_current_site(request)
    meta = Meta(
        title = _('Asociación para la inclusión laboral y atención a la diversidad'),
        description = 'El objetivo principal de la Asociación es especialmente la atención a la plena inclusión social y laboral de las personas con discapacidad intelectual.',
        keywords=['diversidad', 'asociación sin ánimo de lucro', 'inclusión', 'teatro', 'APILAD'],
        use_sites=True,
        image='frontend/images/logo.jpeg',
        extra_props={
            'designer': 'ecDesignStudio',
            'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
        },
        extra_custom_props=[
            ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
        ]
    )
    context = {
        'meta':meta,
        'site_key': settings.RECAPTCHA_PUBLIC_KEY if settings.RECAPTCHA_PUBLIC_KEY else None,
    }
    template_name = 'frontend/home.html'
    response = render(request, template_name, context)

    if _should_set_cookie():
        val = "optional cookie set from django"
        response.set_cookie("optional_test_cookie", val)

    return response


def project_igualarte_teatro(request):
    '''View for the project IgualArte: Teatro e Inclusión'''
    current_site = get_current_site(request)
    meta = Meta(
        title = _('IgualArte: Teatro e inclusión, uno de los proyectos de APILAD'),
        description =  'El Proyecto IgualArte: Teatro e Inclusión es una herramienta para aprender, desarrollar y demostrar que el Teatro es un elemento fundamental para la transformación personal y social en el ámbito de la diversidad intelectual',
        keywords=['diversidad', 'asociación sin ánimo de lucro', 'inclusión', 'teatro', 'APILAD'],
        use_sites=True,
        image='frontend/images/logo.jpeg',
        extra_props={
            'designer': 'ecDesignStudio',
            'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
        },
        extra_custom_props=[
            ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
        ]
    )
    context = {
        'meta':meta,
    }
    return render(request, 'frontend/project/igualarte-teatro.html', context)


def event_detail(request, slug):
    '''View for the event detail'''
    event = get_object_or_404(Event, slug=slug)
    meta = Meta(
        title = event.meta_title,
        description = event.meta_description,
        keywords={event.meta_keywords},
        use_sites=True,
        image=event.image.url if event.image else 'frontend/images/logo.jpeg',
        extra_props={
            'designer': 'ecDesignStudio',
            'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
        },
        extra_custom_props=[
            ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
        ]
    )
    context = {
        'meta':meta,
        'event':event
    }
    template_name = 'frontend/page/event_view.html'
    return render(request, template_name, context)

def my_custom_page_not_found_view(request, exception):
    '''Custom 404 view'''
    return render (request, 'errors/404.html', {})

def custom_error_view(request, exception=None):
    '''Custom 500 view'''
    return render(request, "errors/500.html", {})

def custom_permission_denied_view(request, exception=None):
    '''Custom 403 view'''
    return render(request, "errors/403.html", {})

def custom_bad_request_view(request, exception=None):
    '''Custom 400 view'''
    return render(request, "errors/400.html", {})

class PageDetailView(DetailView):
    '''View for the page detail'''
    model = Page
    template_name = 'frontend/page.html'

    def get_context_data(self, **kwargs):
        context = super(PageDetailView, self).get_context_data(**kwargs)
        context['meta'] = self.get_object().as_meta(self.request)
        return context

def latramoya_view(request):
    '''View for the page La Tramoya'''
    meta = Meta(
        title = _('La Tramoya, historia de un centro Ocupacional de Madrid'),
        description = 'La Tramoya surge en 1992 como una actividad terapéutica e inclusiva dentro de un Centro Ocupacional.La actividad se fue consolidando con el tiempo hasta llegar a conformarse en el año 2000 como compañía estable.',
        keywords=['actividad', 'terapéutica', 'centro ócupacional', 'teatro'],
        use_sites=True,
        image='frontend/images/logo.jpeg',
        extra_props={
            'designer': 'ecDesignStudio',
            'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
        },
        extra_custom_props=[
            ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
        ]
    )
    context = {
        'meta':meta,
    }
    return render(request, 'frontend/page/tramoya.html', context)


def event_list(request):
    '''View for the event list'''
    meta = Meta(
        title = _('Listado de eventos de la Asociación APILAD'),
        description = 'La página de listado de eventos ofrece una amplia variedad de opciones para explorar y participar en eventos emocionantes.',
        keywords=['actividad', 'terapéutica', 'centro ocupacional', 'teatro'],
        use_sites=True,
        image='frontend/images/logo.jpeg',
        extra_props={
            'designer': 'ecDesignStudio',
            'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
        },
        extra_custom_props=[
            ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
        ]
    )
    event_list = Event.objects.exclude(status__in={'o','d'}).order_by('-status', 'order')
    if not event_list:
        messages.error(request, _('Sin eventos que mostrar'))
        return redirect('frontend:home')
    context = {
        'event_list':event_list,
        'meta': meta
    }
    template_name = 'frontend/page/event_list.html'
    return render(request, template_name, context)


def organigramme_view(request):
    '''View for the page Organigramme'''
    meta = Meta(
        title = _('Organigrama de la Asociación APILAD'),
        description = 'El organigrama de la Asociación APILAD muestra la estructura de la Asociación y el equipo de trabajo',
        keywords=['actividad', 'terapéutica', 'centro ocupacional', 'teatro'],
        use_sites=True,
        image='frontend/images/logo.jpeg',
        extra_props={
            'designer': 'ecDesignStudio',
            'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
        },
        extra_custom_props=[
            ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
        ]
    )
    context = {
        'meta':meta,
    }
    return render(request, 'frontend/page/organigramme.html', context)


def team_professional_view(request):
    '''View for the page Equipo Profesional'''
    meta = Meta(
        title = _('Equipo Profesional de la Asociación APILAD'),
        description = 'El equipo profesional de la Asociación APILAD está formado por un grupo de profesionales comprometidos con la inclusión social y laboral de las personas con discapacidad intelectual',
        keywords=['actividad', 'terapéutica', 'centro ocupacional', 'teatro'],
        use_sites=True,
        image='frontend/images/logo.jpeg',
        extra_props={
            'designer': 'ecDesignStudio',
            'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
        },
        extra_custom_props=[
            ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
        ]
    )
    context = {
        'meta':meta,
    }
    return render(request, 'frontend/page/team_professional.html', context)


def team_volunteer_view(request):
    '''View for the page Equipo de Voluntarios'''
    meta = Meta(
        title = _('Equipo de Voluntarios de la Asociación APILAD'),
        description = 'El equipo de voluntarios de la Asociación APILAD está formado por un grupo de personas comprometidas con la inclusión social y laboral de las personas con discapacidad intelectual',
        keywords=['actividad', 'terapéutica', 'centro ocupacional', 'teatro'],
        use_sites=True,
        image='frontend/images/logo.jpeg',
        extra_props={
            'designer': 'ecDesignStudio',
            'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
        },
        extra_custom_props=[
            ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
        ]
    )
    context = {
        'meta':meta,
    }
    return render(request, 'frontend/page/collaborate.html', context)

apps/frontend/templates/frontend/inc/_cookie_body.html
{% load i18n %}
{% load static %}
{% spaceless %}
<div class="cookie-overlay">
    <div class="cookie-body">
        <div class="text-center mb-3">
            <img class="img-fluid" width="150px" src="{% static 'frontend/images/logos/logo.png' %}" alt="{{ app_name }} logo">
        </div>
        <div class="cookie-text">
            {% url 'frontend:page' 'politica-de-cookies' as politicas_cookies %}
            {% blocktrans with url_cookies=politicas_cookies %}
                Apilad utiliza cookies y tecnologías similares para ofrecer, mantener y mejorar nuestros servicios. Si estás de acuerdo, utilizaremos estos datos para mejorar vuestra experiencia en la web. Puedes seleccionar 'Aceptar' para dar tu consentimiento a estos usos, o 'Rechazar' para no darlo. Puedes cambiar tu selección en 'Administrar preferencias de cookies' en la parte inferior de esta página. <a href="{{ url_cookies }}" target="_COOKIES" title="política de cookies">Políticas de Cookies</a>
            {% endblocktrans %}
        </div>
        <div class="cookie-buttons">
            <a href="{{ url_accept }}" class="cc-cookie-accept bnp_btn_accept">{% trans "aceptar"|title %}</a>
            <a href="{{ url_decline }}" class="cc-cookie-decline bnp_btn_reject">{% trans "Rechazar"|title %}</a>
        </div>
    </div>
    {% comment %}
        <a href="{{ url_cookies }}">Cookies info</a>
    {% endcomment %}
</div>
{% endspaceless %}

apps/frontend/templates/frontend/inc/banner-home.html
{% load i18n %}
{% load static %}

<style>
.sect {
  width: 100%;
  min-height: 500px;
}
#sect1 {
  position: relative;
  overflow: hidden;
}
video {
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  z-index: -1;
}
</style>

<div class="banner text-center" id="sect1" class="sect">
    <video src="{% static 'frontend/video/Banner.MP4' %}" autoplay="true" muted="true" loop="true"></video>
    <div class="container">
        <div class="row">
            <div class="col-lg-5 mt-5 mx-auto">
              <h2 class="banner-title" style="border-top: 3px solid white; border-bottom: 3px solid white; padding: 10px 0;">{{ app_name }}</h2>
            </div>
            <div class="col-lg-9 mx-auto">
                <h1 class="mb-5 mt-5 banner-title">{% trans "Asociación Para la Inclusión Laboral de las personas con Discapacidad Intelectual" %}</h1>
            </div>
        </div>
    </div>
</div>

apps/frontend/templates/frontend/inc/block-event-item.html
{% load i18n %}
{% load thumbnail %}

{% if position == 'vertical' %}
  <div class="col-lg-4 mb-5">
    <div class="card {% if event.status == 'f' %}finished{% endif %}">
      {% if event.status == 'f' %}
        <div style="text-align: center;border: 1px solid black" class="text-finished">
          {% trans "evento concluido"|title %}
        </div>
      {% endif %}
      <div class="post-slider slider-sm">
        {% thumbnail event.image "400x400" crop="center" as im %}
          <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="card-img-top" alt="{{ event.title }}">
        {% endthumbnail %}
      </div>
      <div class="card-body">
        <h3 class="h4 mb-3">
          <a class="post-title" href="{% url 'frontend:event_detail' event.slug %}">{{ event.title }}</a>
        </h3>
        <ul class="card-meta list-inline">
            {% if event.text_show_geo %}
                <li class="list-inline-item">
                    <i class="ti-world"></i> {{ event.text_show_geo }}
                </li>
            {% endif %}
            {% if event.text_show_date %}
                <li class="list-inline-item">
                    <i class="ti-calendar"></i>{{ event.text_show_date }}
                </li>
            {% endif %}
        </ul>
        {{ event.description_short|truncatechars:100 }}
        <br>
      </div>
      <div class="card-buttons">
      {% if event.ticket_purchase_link and event.status != 'f'%}
          <a href="{{ event.ticket_purchase_link }}" class="btn btn-outline-primary mb-1" target="_BLANK">{% trans "comprar entrada" %}</a>
      {% endif %}
      {% if event.status == 'f' %}
        <a href="{% url 'frontend:event_detail' event.slug %}" class="btn btn-outline-default">{% trans "ver más" %}</a>
      {% else %}
        <a href="{% url 'frontend:event_detail' event.slug %}" class="btn btn-outline-primary">{% trans "ver más" %}</a>
      {% endif %}
      </div>
    </div>
  </div>
{% elif position == 'horizontal' %}
  <div id="id_{{event.pk }}" class="card mb-4 isotope-item {% if event.status == 'f' %}finished{% endif %}">
      <div class="row card-body">
          <div class="col-md-3 mb-4 mb-md-0">
            {% thumbnail event.image "200x250" crop="center" as im %}
              <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="card-img" alt="{{ event.title }}">
            {% endthumbnail %}
          </div>
          <div class="col-md-8">
            <h3 class="h4 mb-3"><a class="post-title" href="{{ event.get_absolute_url }}">{{ event.title }}</a></h3>
            <ul class="card-meta list-inline">
              {% if event.text_show_geo %}
                <li class="list-inline-item">
                  <i class="ti-map"></i> {{ event.text_show_geo }}
                </li>
              {% endif %}
              {% if event.text_show_date %}
                <li class="list-inline-item">
                  <i class="ti-calendar"></i>{{ event.text_show_date }}
                </li>
              {% endif %}
            </ul>
            <p>{{ event.description_short|truncatewords:36 }}</p>
            <div class="card-buttons">
              {% if event.ticket_purchase_link and event.status != 'f'%}
                  <a href="{{ event.ticket_purchase_link }}" class="btn btn-outline-primary mb-1" target="_BLANK">{% trans "comprar entrada" %}</a>
              {% endif %}
              <a href="{% url 'frontend:event_detail' event.slug %}" class="{% if event.status == 'f' %}btn btn-outline-default{% else %}btn btn-outline-primary{% endif %} mb-1">{% trans "ver más" %}</a>
            </div>
          </div>
      </div>
  </div>
{% endif %}

apps/frontend/templates/frontend/inc/favicons.html
{% load static %}

<link rel="apple-touch-icon" sizes="180x180" href="{% static '/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static '/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static '/favicon-16x16.png' %}">
<link rel="manifest" href="{% static '/site.webmanifest' %}">
<link rel="mask-icon" href="{% static '/safari-pinned-tab.svg' %}" color="#5bbad5">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-config" content="/static/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

apps/frontend/templates/frontend/inc/navigation.html
{% load i18n %}
{% load blog_tags %}

<ul class="navbar-nav">
    {% comment %}
      <li class="nav-item dropdown">
        <a class="nav-link" href="{% url 'frontend:home' %}" >
          {% trans "Inicio" %}
        </a>
      </li>
    {% endcomment %}
    <li class="nav-item dropdown">
      <a class="nav-link">
        {% trans "¿quienes somos?"|upper %}
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'frontend:page' 'quienes-somos' %}">{% trans "nosotros"|title %}</a>
        <a class="dropdown-item" href="{% url 'frontend:organigramme_view' %}">{% trans "organigrama"|title %}</a>
        <a class="dropdown-item" href="{% url 'frontend:team_professional_view' %}">{% trans "equipo de profesional"|title %}</a>
        <a class="dropdown-item" href="{% url 'frontend:team_volunteer_view' %}">{% trans "colaboradores"|title %}</a>
      </div>
    </li>
    {% comment %}
      <li class="nav-item dropdown">
        <a class="nav-link" href="{% url 'frontend:home' %}" >
          {% trans "qué hacemos"|upper %}
        </a>
      </li>
    {% endcomment %}
    <li class="nav-item dropdown">
      <a class="nav-link" href="{% url 'frontend:event_list' %}" >
        {% trans "Eventos"|upper %}
      </a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link" href="{% url 'frontend:home' %}#section-collaborate" >
        {% trans "Colaborar"|upper %}
      </a>
    </li>
    {% blog_menu %}
    <li class="nav-item dropdown">
      <a class="nav-link" href="{% url 'frontend:home' %}#section-contact" >
        {% trans "Contactar"|upper %}
      </a>
    </li>
  </ul>
</div>
<div class="order-2 order-lg-3 d-flex align-items-center">
    <button class="navbar-toggler border-0 order-1" type="button" data-toggle="collapse" data-target="#navigation">
        <i class="ti-menu"></i>
    </button>
</div>

apps/frontend/templates/frontend/inc/section-aboutus.html
{% load i18n %}
{% load static %}

<section class="section wave">
<img src="/static/frontend/images/backgrounds/wave-bg.svg" class="wave-bg">
    <div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-8 mx-auto text-center">
        <h2 class="mb-4">{% trans "Inclusión sociolaboral" %}</h2>
        <p class="mb-4">{% trans "El objetivo principal de la asociación es la plena inclusión sociolaboral de las personas con discapacidad intelectual" %}</p>
        <a href="{% url 'frontend:page' 'quienes-somos' %}" class="btn btn-primary">{% trans "Quienes Somos" %}</a>
        </div>
    </div>
    </div>
</section>

apps/frontend/templates/frontend/inc/section-contact.html
{% load i18n %}
{% load static %}
<section class="section" id="section-contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <div class="content mb-5">
                    <h2 id="we-would-love-to-hear-from-you">{% trans "Formulario de Contacto" %}</h2>
                    <p>{% trans 'En el caso de que usted tenga cualquier duda o consulta que desee realizar a APILAD, puede solicitar esta información cumplimentando el cuestionario anexo y recibirá en breve, contestación a través de su dirección de correo electrónico, o bien directamente:' %}</p>
                </div>
                <form method="post" id="contact_form" action="{% url 'contact:home' %}" accept-charset="utf-8">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" type="text" name="name" id="id-name" placeholder="{% trans 'name'|title %}" required />
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="email" name="email" id="id-email" placeholder="{% trans 'email'|title %}" required />
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="telephone" id="id-telephone" placeholder="{% trans 'telephone'|title %}" required />
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" name="text" id="id-text" placeholder="{% trans 'enter your message'|title %}" rows="6" required></textarea>
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="hidden" id="g-recaptcha-response" name="g-recaptcha-response">
                        <input type="checkbox" id="id-terms" name="id-terms" required />
                        <label for="id-terms">{% trans "I have read and accept" %} <a target="_BLANK" href="{% url 'frontend:page' 'politica-de-privacidad' %}" style="color:#C82A54">{% trans "privacy policy"|capfirst %}</a></label>
                    </div>
                    <div class="col-12 text-center">
                        <button class="btn btn-primary" type="submit">{% trans "Send" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

apps/frontend/templates/frontend/inc/section-projects.html
{% load i18n %}
{% load static %}

<section class="section pb-0">
  <div class="container">
    <h2 class="h5 section-title">{% trans "Proyectos" %}</h2>
    <div class="row">
      <div class="col-lg-4 mb-5">
        <div class="card">
          <div class="post-slider slider-sm">
            <img src="{% static 'frontend/images/proyecto_teatro.jpg' %}" class="card-img-top" alt="post-thumb">
          </div>
          <div class="card-body">
            <h3 class="h4 mb-3"><a class="post-title" href="">IgualArte: Teatro e inclusión</a></h3>
            <p>El Proyecto IgualArte: Teatro e Inclusión es una herramienta para aprender ...</p>
            <p>{% trans "Documentos:" %}</p>
            <ul class="card-meta list-inline">
              <li class="list-inline-item">
                <ul class="card-meta-tag list-inline">
                  <li class="list-inline-item"><a target="_BLANK" href="{% static 'frontend/pdf/Ficha_teatro.pdf' %}">{% trans "Ficha" %}</a></li>
                  <li class="list-inline-item"><a target="_BLANK" href="{% static 'frontend/pdf/Triptico_teatro.pdf' %}">{% trans "Tríptico" %}</a></li>
                </ul>
              </li>
            </ul>
          </div>
          <a href="{% url 'frontend:project_igualarte_teatro' %}" class="btn btn-outline-primary">{% trans "ver más" %}</a>
        </div>
      </div>
      <div class="col-lg-4 mb-5">
        <div class="card">
          <div class="post-slider slider-sm">
            <img src="{% static 'frontend/images/proyecto_danza.jpg' %}" class="card-img-top" alt="post-thumb">
          </div>
          <div class="card-body">
            <h3 class="h4 mb-3"><a class="post-title" href="">IgualArte: Danza e inclusión</a></h3>
            <p>El Proyecto IgualArte: Danza e Inclusión es una herramienta para aprender ...</p>
            <p>{% trans "Documentos:" %}</p>
            <ul class="card-meta list-inline">
              <li class="list-inline-item">
                <ul class="card-meta-tag list-inline">
                  <li class="list-inline-item"><a target="_BLANK" href="{% static 'frontend/pdf/Ficha_danza.pdf' %}">{% trans "Ficha" %}</a></li>
                  <li class="list-inline-item"><a target="_BLANK" href="{% static 'frontend/pdf/Triptico_danza.pdf' %}">{% trans "Tríptico" %}</a></li>
                </ul>
              </li>
            </ul>
          </div>
          <a href="" class="btn btn-outline-primary disabled">{% trans "próximamente"|title %}</a>
        </div>
      </div>
      <div class="col-lg-4 mb-5">
        <div class="card">
          <div class="post-slider slider-sm">
            <img src="{% static 'frontend/images/proyecto_cafe.jpg' %}" class="card-img-top" alt="post-thumb">
          </div>
          <div class="card-body">
            <h3 class="h4 mb-3"><a class="post-title" href="">Visión Café: Barismo e inclusión</a></h3>
            <p>Con el café como pretexto, el proyecto Visión Café: Barismo e Inclusión ...</p>
            <p>{% trans "Documentos:" %}</p>
            <ul class="card-meta list-inline">
              <li class="list-inline-item">
                <ul class="card-meta-tag list-inline">
                  <li class="list-inline-item"><a target="_BLANK" href="{% static 'frontend/pdf/Ficha_cafe.pdf' %}">{% trans "Ficha" %}</a></li>
                  <li class="list-inline-item"><a target="_BLANK" href="{% static 'frontend/pdf/Triptico_cafe.pdf' %}">{% trans "Tríptico" %}</a></li>
                </ul>
              </li>
            </ul>
          </div>
          <a class="btn btn-outline-primary disabled">{% trans "próximamente"|title %}</a>
        </div>
      </div>
      <div class="col-12">
        <div class="border-bottom border-default"></div>
      </div>
    </div>
  </div>
</section>